name: docs

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: yarn install

    - name: Build Docs
      run: yarn docs:build

    - name: Deploy to GitHub Pages
      run: cd docs/.vuepress/dist && git init && git add -A && git commit -m 'deploy' && git push -f https://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@github.com/jeamn/vuepress-test.git master:gh-pages
